name: Semver Tagging
description: Semver Tagging

inputs:
  repo-name:
    required: true
    description: Repository Name
  semver-tag:
    required: true
    default: latest
    description: Tag Alias for SHA
  new-version:
    required: false
    description: New Semver Tag

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${AWS_ACCESS_KEY_ID}
        aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Docker pull, retag and push branch
      shell: bash
      if: ${{ inputs.new-version == '' }}
      run: |
        docker pull ${DOCKER_REGISTRY}/${{ inputs.repo-name }}:latest
        docker tag ${DOCKER_REGISTRY}/${{ inputs.repo-name }}:latest  "${{ inputs.repo-name }}:${{ inputs.semver-tag }}"
        "${{ github.action_path }}/retag-and-push.sh" "${{ inputs.repo-name }}" "${{ inputs.semver-tag }}"

    - name: Docker pull, retag and push tag
      shell: bash
      if: "${{ inputs.new-version != '' }}"
      env:
        NEW_TAG: ${{ inputs.new-version }}
      run: |
        docker pull ${DOCKER_REGISTRY}/${{ inputs.repo-name }}:latest
        docker tag ${DOCKER_REGISTRY}/${{ inputs.repo-name }}:latest  "${{ inputs.repo-name }}:${{ inputs.semver-tag }}"
        "${{ github.action_path }}/retag-and-push.sh" "${{ inputs.repo-name }}" "${{ inputs.semver-tag }}"
